### ISSUE TITLE
Cannot find plugin in Resharper 9.1

### ISSUE THREAD

**Issue by jcdekoning** [DevRust/Teapot#6]
Found this plugin yesterday using Google, and I believe it exactly the functionality what I need. The only problem is that the plugin is not available through the extension manager of Resharper 9.1. Does this have something to do that the plugin is for Wave version 1, and Resharper 9.1 needs Wave 2.0?

JetBrains ReSharper Ultimate 2015.1.3 Build 102.0.20150724.141603
ReSharper 9.1.20150724.165328

**Comment by jcdekoning** [comment]
I forked the project to see if I could "upgrade" the plugin myself because for R# 9.1 the SDK should be version 9.0.20150522.81235. But Nuget is failing to do the upgrade because of some kind of bug in VS 2015. https://github.com/NuGet/Home/issues/1021

I will see if I can find a computer here with VS 2013 to do the reference update later.

**Comment by gkinsman** [comment]
Thanks for contributing the update for 9.2. I've also added in a build system (psake) to make turn around much quicker in the future :).
