### ISSUE TITLE
Suggestion: Find Usages should also take generic arguments into account

### ISSUE THREAD

**Issue by jcdekoning** [DevRust/Teapot#8]
With Teapot it is now possible to do a go to implementation which takes into account the generic arguments. It would also be great if Find Usages would to that.

Currently when I choose Find Usages on a method implemented by a generic interface, it shows me a find result of all places this method is used. But It does not filter it based on the generic version that was implemented in the class making the Find Usages not usefull for navigation.

**Comment by gkinsman** [comment]
This is a great idea, and was brought up by a few people a while ago before Teapot was released.

It should be fairly straightforward - I imagine there'll be a similar implementation for FindUsages as for GoToImplementation - we might even be able to reuse some of the logic.

Would you like to have a crack at it? I'm working on a few other things at the moment and trying to focus my time, but I can take a look if you like :)

**Comment by emilol** [comment]
I have a stash for this somewhere I can dust off. I remember there being an issue, but it might be different now in 9.2. I'll take a look this week.

**Comment by gkinsman** [comment]
:+1:

**Comment by emilol** [comment]
I've pushed a change for this, but it could do with another set of eyes. @gkinsman can you take a look and do some more testing in case I've missed something? SHA: 1a9ed7fc831b1a269eb05bfb72f4592a75ceaeb5

**Comment by emilol** [comment]
This is now released in 3.2 - thanks for the suggestion @jcdekoning!
